# Generated by Django 3.0.2 on 2020-02-24 00:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20200223_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estado',
            name='create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='estado',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estadocivil',
            name='create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='estadocivil',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='genero',
            name='create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='genero',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelprofile',
            name='create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='modelprofile',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ocupacion',
            name='create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ocupacion',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='estadocivil',
            name='nombre',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Ciudad'),
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Estado'),
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='estadoCivil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.EstadoCivil'),
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Genero'),
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='nombre',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='ocupacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Ocupacion'),
        ),
        migrations.AlterField(
            model_name='ocupacion',
            name='nombre',
            field=models.CharField(max_length=254),
        ),
    ]
